### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JesperDramsch** [davenquinn/geologic-patterns#2]
This is pretty awesome. Would you mind adding a license, to disambiguate use and reuse?

https://choosealicense.com should be useful here.

**Comment by davenquinn** [comment]
This is definitely a good idea. I've checked in with David Soller at the USGS, who manages the FGDC as a whole, to make sure that the license correctly treats the original data. The work is in the public domain (being ultimately a U.S. federal project) and my additions are significant enough to additionally encumber them. So most likely it will be something like CC0.

**Comment by JesperDramsch** [comment]
Just ping me, when you add it to the repo. It's a neat thing you have going here!

**Comment by davenquinn** [comment]
Hi @JesperDramsch I have added the Creative Commons CC0 license to this work, which faithfully represents both the public-domain status of U.S. government products and my lack of additional claims on the work. Hope this helps!

**Comment by JesperDramsch** [comment]
Awesome! 

Adding it back in right now. This is a super cool project thanks for taking care of it.
